name: frontend-deploy
on: 
    push: 
        branches: 
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ls
            - run: rsync -avz -e "ssh -i ./giang-aws.pem" ./ ubuntu@3.84.177.88:~/my-web/